
export class Signup{

    navigate(url){
        cy.visit(url)
    }

    SignUpButton(){
        cy.get('.shop-menu > .nav > :nth-child(4) > a')
        .click()
    }
    EnterName(name){
        cy.get('[data-qa="signup-name"]')
        .type(name)
    }
    EnterEmail(email){
        cy.get('[data-qa="signup-email"]')
        .type(email)
    }
    SignUp(){
        cy.get('[data-qa="signup-button"]')
        .click(
        )
    }
    SelectGender(){
        cy.get('#id_gender1')
        .click()
    }
    EnterPassword(password){
        cy.get('[data-qa="password"]')
        .type(password)
    }
    DayofBirth(){
        cy.get('[data-qa="days"]')
        .select('4')
    }
    MonthofBirth(){
        cy.get('[data-qa="months"]')
        .select('March')
    }
    YearofBirth(){
        cy.get('[data-qa="years"]')
        .select('1996')
    }
    NewsLetter(){
        cy.get('#newsletter')
        .click()
    }
    SpecialOffer(){
        cy.get('#optin')
        .click()
    }
    FirstName(firstname){
        cy.get('[data-qa="first_name"]')
        .type(firstname)
    }
    LastName(lastname){
        cy.get('[data-qa="last_name"]')
        .type(lastname)
    }
    Company(company){
        cy.get('[data-qa="company"]')
        .type(company)
    }
    Address(address){
        cy.get('[data-qa="address"]')
        .type(address)
    }
    Country(){
        cy.get('[data-qa="country"]')
        .select('Canada')
    }
    State(state){
        cy.get('[data-qa="state"]')
        .type(state)
    }
    City(city){
        cy.get('[data-qa="city"]')
        .type(city)
    }
    ZipCode(zipcode){
        cy.get('[data-qa="zipcode"]')
        .type(zipcode)
    }
    MobileNumber(mobilenumber){
        cy.get('[data-qa="mobile_number"]')
        .type(mobilenumber)

    }
    CreateAccount(){
        cy.get('[data-qa="create-account"]')
        .click()
    }
    Continue(){
        cy.get('[data-qa="continue-button"]')
        .click()
    }
}