name: E2E Tests

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest  # Choose the appropriate runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Choose the desired Node.js version

      - name: Install dependencies
        run: npm i

      - name: Run E2E tests
        run: npm run test:e2e  # Adjust the command as per your project's setup

      - name: Generate test report
        run: npm run generate-report  # Adjust the command to generate the report
